language: java
jdk:
  - openjdk8

# 어느 브랜치에 푸시될 때 수행할지 지정
branches:
  only:
    - main

# 해당 디렉토리에 캐시하여, 같은 의존성은 다음 배포 때부터 다시 받지 않도록 설정
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# main 브랜치에 푸시되었을 때 수행하는 명령어
script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - "xodlf100@gmail.com"